plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/anshida-rinshi/CentroPos/centro-pos-app/out/renderer"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Skipping Netlify build, using local files'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]