/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PickingRouteImport } from './routes/picking'
import { Route as Picker_feedbackRouteImport } from './routes/picker_feedback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PickingRoute = PickingRouteImport.update({
  id: '/picking',
  path: '/picking',
  getParentRoute: () => rootRouteImport,
} as any)
const Picker_feedbackRoute = Picker_feedbackRouteImport.update({
  id: '/picker_feedback',
  path: '/picker_feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/picker_feedback': typeof Picker_feedbackRoute
  '/picking': typeof PickingRoute
  '/pos': typeof PosRoute
  '/purchase': typeof PurchaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/picker_feedback': typeof Picker_feedbackRoute
  '/picking': typeof PickingRoute
  '/pos': typeof PosRoute
  '/purchase': typeof PurchaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/picker_feedback': typeof Picker_feedbackRoute
  '/picking': typeof PickingRoute
  '/pos': typeof PosRoute
  '/purchase': typeof PurchaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/picker_feedback'
    | '/picking'
    | '/pos'
    | '/purchase'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/picker_feedback' | '/picking' | '/pos' | '/purchase'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/picker_feedback'
    | '/picking'
    | '/pos'
    | '/purchase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  Picker_feedbackRoute: typeof Picker_feedbackRoute
  PickingRoute: typeof PickingRoute
  PosRoute: typeof PosRoute
  PurchaseRoute: typeof PurchaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picking': {
      id: '/picking'
      path: '/picking'
      fullPath: '/picking'
      preLoaderRoute: typeof PickingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picker_feedback': {
      id: '/picker_feedback'
      path: '/picker_feedback'
      fullPath: '/picker_feedback'
      preLoaderRoute: typeof Picker_feedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  Picker_feedbackRoute: Picker_feedbackRoute,
  PickingRoute: PickingRoute,
  PosRoute: PosRoute,
  PurchaseRoute: PurchaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
